'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { Languages, Loader2, Sparkles, Subtitles } from 'lucide-react';
import toast from 'react-hot-toast';
import { learningApi } from './learning-api';
import { youtubeIdFromUrl } from './learning-utils';

const cx = (...parts) => parts.filter(Boolean).join(' ');

let youtubeApiPromise = null;

function loadYoutubeApi() {
	if (typeof window === 'undefined') return Promise.reject(new Error('no window'));
	if (window.YT?.Player) return Promise.resolve(window.YT);
	if (youtubeApiPromise) return youtubeApiPromise;
	youtubeApiPromise = new Promise(resolve => {
		const previous = window.onYouTubeIframeAPIReady;
		window.onYouTubeIframeAPIReady = () => {
			if (typeof previous === 'function') previous();
			resolve(window.YT);
		};
		if (!document.getElementById('so7ba-yt-iframe-api')) {
			const tag = document.createElement('script');
			tag.id = 'so7ba-yt-iframe-api';
			tag.src = 'https://www.youtube.com/iframe_api';
			document.body.appendChild(tag);
		}
		if (window.YT?.Player) resolve(window.YT);
	});
	return youtubeApiPromise;
}

function formatTime(seconds) {
	const total = Math.max(0, Math.floor(Number(seconds) || 0));
	const m = Math.floor(total / 60);
	const s = total % 60;
	return `${m}:${String(s).padStart(2, '0')}`;
}

function findActiveCueIndex(cues, time) {
	if (!cues?.length) return -1;
	let active = -1;
	for (let i = 0; i < cues.length; i += 1) {
		const cue = cues[i];
		if (time >= Number(cue.start) && time < Number(cue.end)) return i;
		if (time >= Number(cue.start)) active = i;
	}
	return active;
}

export function LearningVideoPlayer({
	topic,
	path,
	t,
	locale = 'en',
	onPatch,
	readOnly = false,
}) {
	const url = topic.primaryVideoUrl || '';
	const yt = youtubeIdFromUrl(url);
	const hostIdRef = useRef(`yt-host-${topic.id || 'topic'}`);
	const playerRef = useRef(null);
	const cueRefs = useRef({});
	const [currentTime, setCurrentTime] = useState(0);
	const [showTranscript, setShowTranscript] = useState(Boolean(topic.videoTranscript?.cues?.length));
	const [busy, setBusy] = useState('');
	const [selection, setSelection] = useState(null);
	const [termExplain, setTermExplain] = useState(null);
	const [showArabic, setShowArabic] = useState(
		() => Boolean(topic.videoTranscript?.cues?.some(cue => cue.textAr)) || locale?.startsWith?.('ar'),
	);

	const transcript = topic.videoTranscript;
	const cues = transcript?.cues || [];
	const activeIndex = useMemo(() => findActiveCueIndex(cues, currentTime), [cues, currentTime]);

	useEffect(() => {
		if (!yt) return undefined;
		let destroyed = false;
		let pollId = 0;

		loadYoutubeApi()
			.then(YT => {
				if (destroyed) return;
				const host = document.getElementById(hostIdRef.current);
				if (!host) return;
				host.innerHTML = '';
				playerRef.current = new YT.Player(hostIdRef.current, {
					videoId: yt,
					width: '100%',
					height: '100%',
					playerVars: {
						rel: 0,
						modestbranding: 1,
						playsinline: 1,
						enablejsapi: 1,
					},
					events: {
						onReady: () => {
							pollId = window.setInterval(() => {
								try {
									const time = playerRef.current?.getCurrentTime?.();
									if (typeof time === 'number' && !Number.isNaN(time)) {
										setCurrentTime(time);
									}
								} catch {
									/* ignore */
								}
							}, 250);
						},
					},
				});
			})
			.catch(() => {});

		return () => {
			destroyed = true;
			if (pollId) window.clearInterval(pollId);
			try {
				playerRef.current?.destroy?.();
			} catch {
				/* ignore */
			}
			playerRef.current = null;
		};
	}, [yt, topic.id]);

	useEffect(() => {
		if (activeIndex < 0) return;
		const node = cueRefs.current[cues[activeIndex]?.id];
		node?.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
	}, [activeIndex, cues]);

	const seekTo = seconds => {
		try {
			playerRef.current?.seekTo?.(Number(seconds) || 0, true);
			playerRef.current?.playVideo?.();
			setCurrentTime(Number(seconds) || 0);
		} catch {
			/* ignore */
		}
	};

	const loadTranscript = async () => {
		if (!url.trim()) return;
		setBusy('transcript');
		try {
			const result = await learningApi.videoTranscript(url.trim());
			onPatch?.({
				videoTranscript: {
					videoId: result.videoId,
					language: result.language,
					languageName: result.languageName,
					isAutoGenerated: result.isAutoGenerated,
					cues: result.cues || [],
					fetchedAt: new Date().toISOString(),
				},
			});
			setShowTranscript(true);
			setShowArabic(false);
			toast.success(t.transcriptLoaded);
		} catch (error) {
			toast.error(error?.response?.data?.message || t.transcriptLoadFailed);
		} finally {
			setBusy('');
		}
	};

	const translateTranscript = async () => {
		setBusy('translate');
		try {
			let sourceCues = cues.filter(cue => cue?.id && cue?.text);
			let baseTranscript = topic.videoTranscript || null;

			if (!sourceCues.length) {
				if (!url.trim()) return;
				const result = await learningApi.videoTranscript(url.trim());
				baseTranscript = {
					videoId: result.videoId,
					language: result.language,
					languageName: result.languageName,
					isAutoGenerated: result.isAutoGenerated,
					cues: result.cues || [],
					fetchedAt: new Date().toISOString(),
				};
				sourceCues = baseTranscript.cues;
				onPatch?.({ videoTranscript: baseTranscript });
				setShowTranscript(true);
			}

			if (!sourceCues.length) {
				toast.error(t.transcriptLoadFailed);
				return;
			}

			const merged = [...sourceCues];
			const batchSize = 120;
			for (let offset = 0; offset < sourceCues.length; offset += batchSize) {
				const chunk = sourceCues.slice(offset, offset + batchSize);
				const result = await learningApi.ai({
					action: 'translate_transcript',
					locale: 'ar',
					prompt: 'Translate transcript cues to Arabic for learners.',
					context: {
						topicTitle: topic.title,
						pathTitle: path?.title,
						cues: chunk.map(cue => ({ id: cue.id, text: cue.text })),
					},
				});
				const translated = Array.isArray(result?.parsed?.cues) ? result.parsed.cues : [];
				const byId = new Map(
					translated.map(item => [String(item.id), String(item.textAr || '').trim()]),
				);
				for (let i = 0; i < merged.length; i += 1) {
					const ar = byId.get(String(merged[i].id));
					if (ar) merged[i] = { ...merged[i], textAr: ar };
				}
			}

			onPatch?.({
				videoTranscript: {
					...(baseTranscript || {}),
					cues: merged,
					translatedAt: new Date().toISOString(),
				},
			});
			setShowArabic(true);
			setShowTranscript(true);
			toast.success(t.transcriptTranslated);
		} catch (error) {
			toast.error(error?.response?.data?.message || t.transcriptTranslateFailed);
		} finally {
			setBusy('');
		}
	};

	const explainSelection = async () => {
		const term = String(selection?.text || '').trim();
		if (!term) return;
		setBusy('explain');
		try {
			const result = await learningApi.ai({
				action: 'explain_term',
				locale,
				prompt: term,
				context: {
					term,
					topicTitle: topic.title,
					pathTitle: path?.title,
					category: path?.category,
					surrounding: selection?.surrounding || '',
				},
			});
			setTermExplain(result?.parsed || {
				term,
				meaning: result?.reply || '',
				inThisDomain: '',
				simpleExample: '',
				relatedTerms: [],
			});
		} catch (error) {
			toast.error(error?.response?.data?.message || t.termExplainFailed);
		} finally {
			setBusy('');
		}
	};

	const onTranscriptMouseUp = () => {
		if (typeof window === 'undefined') return;
		const selected = String(window.getSelection?.()?.toString() || '').trim();
		if (!selected || selected.length < 2 || selected.length > 80) {
			setSelection(null);
			return;
		}
		const activeCue = cues[activeIndex];
		setSelection({
			text: selected,
			surrounding: activeCue?.text || selected,
		});
		setTermExplain(null);
	};

	if (!yt) {
		return (
			<div className="grid place-items-center rounded-xl border border-dashed border-[var(--learn-border-glass)] px-4 py-10 text-sm text-[var(--learn-ink-soft)]">
				{t.noVideoYet}
			</div>
		);
	}

	return (
		<div className="learning-video-stage">
			<div className="learning-video-stage__player">
				<div id={hostIdRef.current} className="learning-video-stage__host" />
			</div>

			{!readOnly ? (
				<input
					value={url}
					onChange={event => {
						const nextUrl = event.target.value;
						const nextId = youtubeIdFromUrl(nextUrl);
						onPatch?.({
							primaryVideoUrl: nextUrl,
							...(transcript?.videoId && nextId !== transcript.videoId
								? { videoTranscript: null }
								: {}),
						});
						if (nextId !== transcript?.videoId) {
							setShowTranscript(false);
							setShowArabic(false);
							setSelection(null);
							setTermExplain(null);
						}
					}}
					placeholder={t.videoUrlPlaceholder}
					className="learning-neu-inset h-10 w-full px-3 text-sm outline-none"
				/>
			) : null}

			<div className="learning-video-stage__actions">
				<button
					type="button"
					className={cx('learning-video-action', showTranscript && 'is-active')}
					onClick={() => {
						if (!cues.length) loadTranscript();
						else setShowTranscript(value => !value);
					}}
					disabled={busy === 'transcript'}
				>
					{busy === 'transcript' ? <Loader2 size={14} className="animate-spin" /> : <Subtitles size={14} />}
					{showTranscript ? t.hideTranscript : t.showTranscript}
				</button>
				<button
					type="button"
					className="learning-video-action"
					onClick={translateTranscript}
					disabled={Boolean(busy)}
				>
					{busy === 'translate' ? <Loader2 size={14} className="animate-spin" /> : <Languages size={14} />}
					{t.translateTranscriptAr}
				</button>
				{cues.some(cue => cue.textAr) ? (
					<button
						type="button"
						className={cx('learning-video-action', showArabic && 'is-active')}
						onClick={() => setShowArabic(value => !value)}
					>
						{showArabic ? t.showOriginalTranscript : t.showArabicTranscript}
					</button>
				) : null}
			</div>

			{showTranscript ? (
				<div className="learning-video-transcript" onMouseUp={onTranscriptMouseUp}>
					<div className="learning-video-transcript__head">
						<p>{t.transcriptHint}</p>
						{selection?.text ? (
							<button
								type="button"
								className="learning-video-action is-compact"
								onClick={explainSelection}
								disabled={busy === 'explain'}
							>
								{busy === 'explain' ? (
									<Loader2 size={13} className="animate-spin" />
								) : (
									<Sparkles size={13} />
								)}
								{t.explainTerm}: “{selection.text.slice(0, 28)}
								{selection.text.length > 28 ? '…' : ''}”
							</button>
						) : null}
					</div>

					{termExplain ? (
						<aside className="learning-video-term">
							<strong>{termExplain.term || selection?.text}</strong>
							{termExplain.meaning ? <p>{termExplain.meaning}</p> : null}
							{termExplain.inThisDomain ? (
								<p>
									<span>{t.inThisDomain}:</span> {termExplain.inThisDomain}
								</p>
							) : null}
							{termExplain.simpleExample ? (
								<p>
									<span>{t.simpleExample}:</span> {termExplain.simpleExample}
								</p>
							) : null}
							<button type="button" onClick={() => setTermExplain(null)}>
								{t.close}
							</button>
						</aside>
					) : null}

					<div className="learning-video-transcript__list">
						{cues.length === 0 ? (
							<p className="learning-video-transcript__empty">{t.transcriptEmpty}</p>
						) : (
							cues.map((cue, index) => (
								<button
									key={cue.id || `${cue.start}-${index}`}
									type="button"
									ref={node => {
										if (cue.id) cueRefs.current[cue.id] = node;
									}}
									className={cx(
										'learning-video-cue',
										index === activeIndex && 'is-active',
									)}
									onClick={() => seekTo(cue.start)}
								>
									<span className="learning-video-cue__time">{formatTime(cue.start)}</span>
									<span className="learning-video-cue__text">
										{showArabic && cue.textAr ? cue.textAr : cue.text}
									</span>
								</button>
							))
						)}
					</div>
				</div>
			) : null}
		</div>
	);
}
