import { DEFAULT_PARTICLE_CONFIG } from './particle-config';

export const BUILTIN_PRESETS = [
	{
		id: 'default',
		name: 'Default',
		config: { ...DEFAULT_PARTICLE_CONFIG },
	},
	{
		id: 'soft',
		name: 'Soft',
		config: {
			...DEFAULT_PARTICLE_CONFIG,
			count: 10000,
			size: 2.8,
			sizeVariance: 0.4,
			radius: 140,
			strength: 0.55,
			swirl: 0.35,
			spring: 0.7,
			damping: 0.45,
			drift: 0.35,
			floatIntensity: 1.2,
			rotationIntensity: 0.4,
			floatSpeed: 1.2,
		},
	},
	{
		id: 'strong-interaction',
		name: 'Strong Interaction',
		config: {
			...DEFAULT_PARTICLE_CONFIG,
			count: 16000,
			size: 2.2,
			sizeVariance: 0.7,
			radius: 180,
			strength: 2.4,
			swirl: 1.1,
			spring: 1.6,
			damping: 0.22,
			drift: 0.5,
			floatIntensity: 1.5,
			rotationIntensity: 0.8,
		},
	},
	{
		id: 'futuristic',
		name: 'Futuristic',
		config: {
			...DEFAULT_PARTICLE_CONFIG,
			count: 18000,
			size: 1.8,
			sizeVariance: 0.8,
			radius: 150,
			strength: 1.5,
			swirl: 1.2,
			spring: 1.4,
			damping: 0.28,
			drift: 0.4,
			floatIntensity: 0.8,
			rotationIntensity: 0.3,
			floatSpeed: 1,
		},
	},
	{
		id: 'minimal',
		name: 'Minimal',
		config: {
			...DEFAULT_PARTICLE_CONFIG,
			count: 6000,
			size: 3.2,
			sizeVariance: 0.2,
			radius: 100,
			strength: 0.8,
			swirl: 0.2,
			spring: 1.1,
			damping: 0.4,
			drift: 0.15,
			floatIntensity: 0.4,
			rotationIntensity: 0.15,
			floatSpeed: 0.8,
		},
	},
	{
		id: 'explosive',
		name: 'Explosive',
		config: {
			...DEFAULT_PARTICLE_CONFIG,
			count: 22000,
			size: 1.6,
			sizeVariance: 0.9,
			radius: 220,
			strength: 3.5,
			swirl: 1.6,
			spring: 0.9,
			damping: 0.18,
			drift: 0.9,
			floatIntensity: 2.4,
			rotationIntensity: 1.4,
			floatSpeed: 2.2,
			interactionMode: 'explode',
		},
	},
];
