export const DEFAULT_PARTICLE_CONFIG = {
	count: 14000,
	size: 2.4,
	sizeVariance: 0.6,
	color: '',
	radius: 110,
	strength: 1,
	swirl: 0.6,
	spring: 1,
	damping: 0.35,
	drift: 0.6,
	background: '',
	scale: 3,
	xOffset: 0,
	yOffset: 0,
	floatIntensity: 2,
	rotationIntensity: 1,
	floatSpeed: 2,
	orbit: false,
	zoom: false,
	autoRotate: false,
	autoRotateSpeed: 2,
	fov: 65,
	cameraDistance: 4.2,
	cursorEnabled: true,
	interactionMode: 'push',
	useOriginalColors: true,
	initialFormation: true,
	formationDuration: 1.5,
	formationStrength: 1,
	formationEasing: 'power2.out',
	morphDuration: 2,
	morphEasing: 'power2.inOut',
	morphDelay: 0.3,
	alphaThreshold: 10,
	brightness: 0,
	contrast: 0,
	imageScale: 1,
	center: true,
	invertAlpha: false,
};

export const CONTROL_RANGES = {
	count: { min: 1000, max: 50000, step: 500 },
	size: { min: 0.2, max: 8, step: 0.1 },
	sizeVariance: { min: 0, max: 1, step: 0.01 },
	radius: { min: 20, max: 300, step: 1 },
	strength: { min: 0, max: 5, step: 0.05 },
	swirl: { min: 0, max: 2, step: 0.05 },
	spring: { min: 0, max: 5, step: 0.05 },
	damping: { min: 0, max: 1, step: 0.01 },
	drift: { min: 0, max: 3, step: 0.05 },
	floatIntensity: { min: 0, max: 5, step: 0.05 },
	floatSpeed: { min: 0, max: 5, step: 0.05 },
	rotationIntensity: { min: 0, max: 5, step: 0.05 },
	scale: { min: 0.5, max: 8, step: 0.1 },
	xOffset: { min: -3, max: 3, step: 0.05 },
	yOffset: { min: -3, max: 3, step: 0.05 },
	fov: { min: 20, max: 120, step: 1 },
	cameraDistance: { min: 1, max: 12, step: 0.1 },
	autoRotateSpeed: { min: 0, max: 10, step: 0.1 },
	formationDuration: { min: 0.2, max: 5, step: 0.1 },
	formationStrength: { min: 0, max: 3, step: 0.05 },
	morphDuration: { min: 0.3, max: 8, step: 0.1 },
	morphDelay: { min: 0, max: 5, step: 0.1 },
	alphaThreshold: { min: 0, max: 255, step: 1 },
	brightness: { min: -100, max: 100, step: 1 },
	contrast: { min: -100, max: 100, step: 1 },
	imageScale: { min: 0.2, max: 2, step: 0.05 },
};

export const INTERACTION_MODES = [
	{ id: 'push', label: 'Push' },
	{ id: 'repel', label: 'Repel' },
	{ id: 'swirl', label: 'Swirl' },
	{ id: 'attract', label: 'Attract' },
	{ id: 'orbit', label: 'Orbit' },
	{ id: 'explode', label: 'Explode' },
];

export function createEmptyScene(name = 'Untitled Scene') {
	return {
		id: `scene-${Date.now()}`,
		name,
		assets: [],
		morphTargets: [],
		config: { ...DEFAULT_PARTICLE_CONFIG },
		timeline: {
			playing: false,
			currentIndex: 0,
			progress: 0,
		},
	};
}

export function createAssetMeta({
	id,
	name,
	filename,
	url,
	type,
	count = DEFAULT_PARTICLE_CONFIG.count,
	objectUrl = null,
}) {
	return {
		id: id || `asset-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
		name: name || filename || 'Untitled',
		filename: filename || '',
		url: url || '',
		objectUrl,
		type: type || 'image',
		count,
	};
}
